import CogIcon from '@sanity/icons/Cog'
import { defineArrayMember, defineField, defineType } from 'sanity'
import { imageFields } from './imageFields'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  icon: CogIcon,
  groups: [
    { name: 'identity', title: 'Identity & hero', default: true },
    { name: 'about', title: 'About' },
    { name: 'contact', title: 'Contact & links' },
    { name: 'navigation', title: 'Navigation & footer' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'fullName',
      title: 'Full name',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'professionalTitle',
      title: 'Professional title',
      type: 'string',
      group: 'identity',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero headline',
      type: 'string',
      group: 'identity',
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero description',
      type: 'text',
      rows: 3,
      group: 'identity',
    }),
    defineField({
      name: 'heroTags',
      title: 'Hero supporting labels',
      description: 'Optional short labels shown under the hero text.',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
      group: 'identity',
    }),
    defineField({
      name: 'profileImage',
      title: 'Profile image',
      type: 'image',
      options: { hotspot: true },
      fields: imageFields,
      group: 'identity',
    }),
    defineField({
      name: 'aboutSummary',
      title: 'About summary (homepage)',
      description: 'Short text for the homepage about section.',
      type: 'text',
      rows: 4,
      group: 'about',
    }),
    defineField({
      name: 'aboutHeadline',
      title: 'About page headline',
      type: 'string',
      group: 'about',
    }),
    defineField({
      name: 'aboutText',
      title: 'About page content',
      type: 'blockContent',
      group: 'about',
    }),
    defineField({
      name: 'email',
      type: 'string',
      validation: (rule) => rule.email(),
      group: 'contact',
    }),
    defineField({ name: 'location', type: 'string', group: 'contact' }),
    defineField({
      name: 'githubUrl',
      title: 'GitHub URL',
      type: 'url',
      validation: (rule) => rule.uri({ scheme: ['https'] }),
      group: 'contact',
    }),
    defineField({
      name: 'linkedinUrl',
      title: 'LinkedIn URL',
      type: 'url',
      validation: (rule) => rule.uri({ scheme: ['https'] }),
      group: 'contact',
    }),
    defineField({
      name: 'cv',
      title: 'CV (PDF)',
      description: 'The Download CV button always uses the latest upload.',
      type: 'file',
      options: { accept: 'application/pdf' },
      group: 'contact',
    }),
    defineField({
      name: 'contactHeadline',
      title: 'Contact section headline',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactDescription',
      title: 'Contact section description',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'navigation',
      title: 'Navigation links',
      description: 'Leave empty to use the default links.',
      type: 'array',
      group: 'navigation',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'navItem',
          fields: [
            defineField({
              name: 'label',
              type: 'string',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'href',
              type: 'string',
              description: 'Path such as /projects or /#experience.',
              validation: (rule) =>
                rule.required().regex(/^[/#]/, { name: 'internal path' }),
            }),
          ],
          preview: { select: { title: 'label', subtitle: 'href' } },
        }),
      ],
    }),
    defineField({
      name: 'footerText',
      title: 'Footer text',
      type: 'string',
      group: 'navigation',
    }),
    defineField({
      name: 'siteTitle',
      title: 'Site title',
      description:
        'Default browser/search title, e.g. "Name | Software Engineer".',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'defaultMetaDescription',
      title: 'Default meta description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.max(160).warning('Keep under 160 characters.'),
      group: 'seo',
    }),
    defineField({
      name: 'ogImage',
      title: 'OpenGraph image',
      description: 'Recommended 1200×630.',
      type: 'image',
      fields: imageFields,
      group: 'seo',
    }),
  ],
  preview: { prepare: () => ({ title: 'Site settings' }) },
})
